### PR TITLE
Delete Polish translation

### PR DESCRIPTION
**Pull request by rob006**
These translations are outdated and this extension is already translated in Polish language pack: https://github.com/rob006-software/flarum-lang-polish/blob/master/locale/malago-ads.yml

### CODE REVIEW

**Comment by rob006** [comment]
BTW: What is the status of Spanish translation: https://github.com/malago86/flarum-ads/blob/main/resources/locale/es.yml ?

I'm trying to remove redundant translations from [Weblate](https://weblate.rob006.net/projects/flarum/), so translations already maintained by extension author will not be duplicated by language pack maintainers.

**Comment by rob006** [comment]
@malago86 Any feedback on this?

**Comment by rob006** [comment]
@malago86 Thanks. How about Spanish translation? I see you're updating it for https://github.com/malago86/flarum-achievements, bot in this repo Spanish translation was not updated to [the last changes](https://github.com/malago86/flarum-ads/commit/4a05fd9c862b27b15734e2299ee680dc5f312344#diff-2fc8643b9ebb3b1f9f8f8064804db6bfa8cce56e4f30fb244a132cc04bad15a9R22).

**Comment by malago86** [comment]
I'm just going to delete all the translations. I believe they should be maintained by the translation extensions.

**Comment by rob006** [comment]
I you're able to maintain them on your own (without relying on outside contributors), it is probably better to keep them in extension repository, since it allows to avoid some issues that may happen if you rely on language packs. In other case indeed it is better to keep translations in language packs.

**Pull request merged**
